project_id = "mmlizntmpbriyumsunsh"

[functions.improvise]
verify_jwt = false

[functions.piano-ask]
verify_jwt = false

[functions.piano-learn]
verify_jwt = false

[functions.piano-evaluate]
verify_jwt = false

[functions.curriculum-publish]
verify_jwt = false
